language: c
sudo: false
git:
  submodules: false
notifications:
  irc: "irc.freenode.net#haskell-raaz"
  on_success: always
  on_failure: always
  use_notice: false
  skip_join: false

# Setting up caches
before-cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

fast_finish: true

addons:
  apt:
    packages:
      - libgmp-dev

      - ghc-8.2.2
      - cabal-install-2.0

      - ghc-head
      - cabal-install-head

      - hlint
    sources: [hvr-ghc]

matrix:
  include:

    - os: osx

    - os: linux
      env: GHCVER=8.2.2 CABALVER=2.0

    # Build with stack package sets
    - os: linux
      env: GHCVER=8.2.2 CABALVER=2.0 STACKVER=lts

    - os: linux
      env: GHCVER=8.2.2 CABALVER=2.0 STACKVER=nightly

    # Build for the GHC head and cabal-install-head
    - os: linux
      env: GHCVER=head CABALVER=head
    # Lint the code.
    - os: linux
      env: HLINT="yes"

  allow_failures:
    - env: GHCVER=head CABALVER=head
    - env: HLINT="yes"

before_install:
 - uname -a
 - if [ "$HLINT" == "yes" ]; then
      hlint "--ignore=Parse error" Raaz;
      exit $?;
   fi


 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;

 - if [ -n "$STACKVER" ]; then ./scripts/stack-freeze.sh "$STACKVER"; fi # Sets up the appropriate freeze.
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ghc cabal-install z3; fi
 - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew info ghc cabal-install z3 ; fi

install:
 - cabal --version
 - travis_retry cabal update;

script:
  - cabal new-configure --flag='-linux-getrandom'
  - cabal new-build
  - cabal new-test
  - cabal check
  - if [ "$CABALVER" == "head" ]; then cabal new-run raaz info; fi
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - backpack
    - release-0.2.0
