# Sample Appveyor file from https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
build: off
environment:
  global:
    CABALVER: "2.0.0.1"
    GHCVER:   "8.2.2"
    STACK_SNAPSHOT: "lts"
  matrix:
    - ARCH: x86_64
    - ARCH: i386

clone_folder: "c:\\raaz"
before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- set GHCURL=https://downloads.haskell.org/~ghc/%GHCVER%/ghc-%GHCVER%-%ARCH%-unknown-mingw32.tar.xz
- set CABALURL=https://www.haskell.org/cabal/release/cabal-install-%CABALVER%/cabal-install-%CABALVER%-%ARCH%-unknown-mingw32.zip
- set STACKAGE_URL=https://www.stackage.org/%STACK_SNAPSHOT%/cabal.config
- curl -sS -ocabal.zip %CABALURL%
- curl -sS -oghc.txz  %GHCURL%
- 7z x cabal.zip
- 7z x ghc.txz
- 7z x ghc.tar
- set PATH=%APPVEYOR_BUILD_FOLDER%;%APPVEYOR_BUILD_FOLDER%\ghc-%GHCVER%\bin;%PATH%
- cabal --version
- ghc   --version
- cabal update
- curl -S -ocabal.project.freeze %STACKAGE_URL%

test_script:
- cabal new-configure --enable-tests --enable-benchmarks
- cabal new-build
- cabal new-test
- cabal check

branches:
  only:
    - master
    - backpack
    - release-0.2.0
