# Sample Appveyor file from https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
build: off
environment:
  global:
    STACK_ROOT: "c:\\sr"
    CABALVER: "2.0.0.1"
    GHCVER:   "8.2.2"
  matrix:
    - ARCH: x86_64
    - ARCH: i386

clone_folder: "c:\\raaz"
before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- set GHCURL=https://downloads.haskell.org/~ghc/%GHCVER%/ghc-%GHCVER%-%ARCH%-unknown-mingw32.tar.xz
- set CABALURL=https://www.haskell.org/cabal/release/cabal-install-%CABALVER%/cabal-install-%CABALVER%-%ARCH%-unknown-mingw32.zip
- curl -S -ocabal.zip %CABALURL%
- curl -S -oghc.txz  %GHCURL%
- curl -S -ostack.zip -L --insecure http://www.stackage.org/stack/windows-%ARCH%
- 7z x stack.zip stack.exe
- 7z x cabal.zip
- 7z x ghc.txz
- set PATH=%APPVEYOR_BUILD_FOLDER%;%APPVEYOR_BUILD_FOLDER%\ghc-%GHCVER%\bin;%PATH%
- cabal --version
- ghc   --version
- echo Some information of interest
- echo %PATH%
- pwd

test_script:
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test --arch %ARCH%
- stack exec raaz info

branches:
  only:
    - master
    - backpack
    - release-0.2.0
