# Sample Appveyor file from https://www.snoyman.com/blog/2016/08/appveyor-haskell-windows-ci
build: off
environment:
  global:
    GHCVER:   "8.2.2"
    STORE_DIR: "c:\\s"
  matrix:
    - ARCH_SEL_FLAG: ""    # Default
    - ARCH_SEL_FLAG: --x86 # Select 32-bit builds

clone_folder: "c:\\raaz"
before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- choco install -y %ARCH_SEL_FLAG% ghc --version %GHCVER%
- ghc --info | sls platform
- refreshenv
- cabal --version
- ghc   --version
- cabal update

test_script:
- cabal --store-dir=%STORE_DIR% new-configure > nul
- cabal --store-dir=%STORE_DIR% new-build
- cabal --store-dir=%STORE_DIR% new-test

branches:
  only:
    - master
    - backpack
    - release-0.2.0
